# Generated by Django 2.1.3 on 2018-12-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_from', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('flight_type', models.IntegerField(choices=[(0, 'Business class'), (1, 'First class')], default=0)),
                ('ticket_type', models.IntegerField(choices=[(0, 'Return ticket'), (1, 'One way')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (0, 'Male'), (2, 'Unkonwn')])),
                ('passport_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('contact_next_of_kin_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('contact_next_of_kin_relationship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relationship')),
                ('contact_next_of_kin_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('contact_next_of_kin_mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile')),
                ('contact_next_of_kin_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flight.Flight')),
            ],
        ),
    ]
