# Generated by Django 2.1.3 on 2018-12-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0002_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
